# Generated by Django 5.1 on 2024-09-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_quizprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='progress',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
