# Generated by Django 5.1 on 2024-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lesson_category_lesson_lesson_type_lesson_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprogress',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
