# Generated by Django 5.1 on 2024-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='completed_content',
            field=models.ManyToManyField(blank=True, related_name='completed_progress_content', to='core.content'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_progress', to='core.module'),
        ),
    ]
