# Generated by Django 5.1 on 2024-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_courseprogress_completed_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='Untitle Content', max_length=255),
        ),
    ]
