# Generated by Django 5.1 on 2024-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_content_module_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
