# Generated by Django 5.1 on 2024-10-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_quiz_lesson_quiz_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.content'),
        ),
    ]
